In [1]:
import pandas as pd
import numpy as np
print('ctest')

ctest

In [ ]:
train_df = pd.read_csv('s3://nmlt201021/EEGTest.csv')
train_df

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,time,event,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10,ch11,ch12,ch13,ch14,ch15,ch16
0,0,16-17-29.928303,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0,0.0,1.0,45078.484127,46072.846183,18896.768260,12558.484084,25179.888329,29435.101680,26219.803240,21037.126605,20408.930827,21152.349848,18411.154260,27209.449078,37855.272037,15765.691193,42836.805324,25845.724445
2,1,0.0,1.0,90105.648649,92085.834394,37736.919551,25051.365799,50410.179843,58695.032739,52504.940630,41999.754846,39966.930743,41161.765595,35929.088107,52932.730667,72978.624461,34298.953032,79826.617816,48579.996655
3,2,0.0,1.0,90138.617472,92104.855729,37740.853458,25066.654392,50462.974663,58950.200254,52424.027315,42069.000550,39940.220408,41149.449783,35856.824917,52938.050382,73607.379032,34594.688963,79803.640223,48627.181188
4,3,0.0,1.0,90129.341499,92133.980052,37766.401501,25077.807913,50546.994871,58669.507047,52510.886194,42005.096913,39994.356334,41190.353476,35926.338843,52958.971615,73546.582287,34361.649676,79844.968598,48606.103493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42019,1017,99,1.0,83826.440135,85575.955877,26415.649225,11223.324981,42344.798725,49462.309416,52555.299110,42863.426252,28700.377488,26872.921213,20116.167678,35936.330072,75565.145977,6287.322198,81022.503200,61883.710251
42020,1018,99,1.0,83780.462596,85530.648891,26386.681364,11200.146222,42320.256510,49653.752107,52579.014311,43136.385755,28704.087878,26840.399425,20162.122865,35907.809247,75368.897661,6224.223223,81022.883180,61620.227888
42021,1019,99,1.0,83817.119457,85564.578839,26431.898943,11216.462996,42340.060155,49483.498869,52581.137726,42952.006215,28636.764423,26847.261411,20097.593379,35922.561398,75947.852546,6265.752764,80998.586833,61846.472245
42022,1020,99,1.0,83809.296347,85554.319388,26427.942685,11213.512565,42332.549969,49619.039848,52577.695558,43044.587141,28687.480532,26841.293495,20179.423115,35919.655671,75564.989515,6226.883081,81032.740299,61582.162867
42023,1021,99,1.0,83819.086411,85553.537077,26435.966961,11202.314341,42336.349766,49501.044989,52583.507011,43009.405495,28659.294982,26861.857100,20113.686635,35953.540916,76218.487468,6293.468928,80999.279737,61820.432463